### ISSUE TITLE
Latest beta?

### ISSUE THREAD

**Issue by Jayphen** [liamcain/AutoFileName#2]
Is this working in the latest beta? I can't seem to get it to trigger. Does it work inside SASS/HAML?

**Comment by liamcain** [comment]
What OS are you using?

**Comment by Jayphen** [comment]
Sorry, I'm using OS X

**Comment by liamcain** [comment]
hmmm.  I'm using OSX on the latest beta as well.  Try pressing control+space to activate.  Because AutoFileName just integrates into the default autocomplete, it uses a couple of simple if statements to know when to trigger.  First it checks that the previous character is / or .  So if you have something like `<a link="/[CURSOR HERE]"> </a>`, it will activate on control space.  That way there arent so many false positives if you are inside a string and don't want to see your filesystem.  Let me know if that helps.  If not, could you give me a sample of your code that you are trying to use it with?  Just the current line will do, to get this straightened out in case it's a bug.

**Comment by liamcain** [comment]
Did you get it working?

**Comment by Jayphen** [comment]
Hey, yeah it did work after pressing ctrl + space, but it conflicts with my shortcut for Launchbar, which is why it wasn't working before. Thanks!
